### ISSUE TITLE
Mejorar el readme

### ISSUE THREAD

**Issue by pedabraham** [devzcommunity/community#23]
Hola Devz, me gustaría saber si me permiten darle un poco de estructura al readme.
Lo que propongo es:
- Poner un encabezado.
- Una ligera introducción.
- Pequeña descripción de los archivos en el repo.
- Ligas a los otros canales de la comunidad como slack, blog, twitter y Facebook.

**Comment by ivanebernal** [comment]
Hola Pedro! Adelante, puedes hacer tu branch y hacer un PR para que los moderadores lo revisemos.
